language: csharp
mono: none
dotnet: 2.0.3
dist: trusty
script:
 - dotnet restore
 - dotnet build -c Release
 - nuget pack Zuehlke.Hades/Zuehlke.Hades.nuspec
 - nuget pack Zuehlke.Hades.SqlServer/Zuehlke.Hades.SqlServer.nuspec